### PR TITLE
BTSs listen on port 5080

### PR DESCRIPTION
**Pull request by kheimerl**
BTS's listen on port 5080, but this wasn't represented in the inendaga call plan.

### CODE REVIEW

**Comment by kkroo** [comment]
is this openbts specific?

**Comment by kheimerl** [comment]
Not as far as I know, I think all bts's listed on port 5080 for endaga traffic

**Comment by kheimerl** [comment]
https://github.com/facebookincubator/CommunityCellularManager/blob/master/client/conf/freeswitch-conf-endaga/freeswitch/vars.xml#L304

**Comment by kkroo** [comment]
The code pointer checks out but I am still skeptical as to how this is working in production

**Comment by kheimerl** [comment]
It's not, we don't call between nodes now I think

mobile

**Comment by kkroo** [comment]
gotcha, just realized this is the bts dialplan profile. thought it was the public profile

**Pull request closed without merging**
