### PR TITLE
[osmocom-python] Explicitly track development requirements

### PR DESCRIPTION
**Pull request by matt9j**
This commit explicitly tracks common developer packages (nose and
mock) to allow for automated continuous integration of
osmocom-python's tests.

### CODE REVIEW

**Comment by shaddi** [comment]
Thanks for this PR. Could you please update these to `>=` dependencies? I think tracking base requirements is good, but I'm not sure they need to be specifically tied to these versions.

**Comment by matt9j** [comment]
@shaddi Updates have been made! The versions I pinned were not chosen specifically, but just happen to be the versions most up to date on pypi right now. Older versions could probably be used as the requirement, but I didn't taken the time to go back and see what features are specifically required by the module. I have tested with these versions on my local machine and on Travis, so base-lining here should be okay going forward.

**Comment by shaddi** [comment]
Awesome, thanks! I know `pip freeze` uses `==` by default for good reason, but I think it's better to be flexible here.

**Comment by matt9j** [comment]
Definitely. We've been using pipenv/pipfiles internally, and they differentiate between the predictability of freeze and the flexibility of specifying softer dependencies. It's a nice upgrade over the default requirements files, but not standardized yet.

**Pull request closed without merging**
